const object ={
  id: 'cs_test_a1x8DTiCWrwsABedIHWDEpcGsyYbLS2rpKLKpwy2SZMaNusrgikkAQBelh',
  object: 'checkout.session',
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 4000,
  amount_total: 4000,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: null,
  cancel_url: 'http://localhost:3000/cancel',
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: null,
  created: 1729559725,
  currency: 'brl',
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null
  },
  customer: 'cus_R4g3xMx8XLkEn5',
  customer_creation: 'always',
  customer_details: {
    address: {
      city: null,
      country: 'BR',
      line1: null,
      line2: null,
      postal_code: null,
      state: null
    },
    email: 'testJubJub@domain.com',
    name: 'teste',
    phone: null,
    tax_exempt: 'none',
    tax_ids: []
  },
  customer_email: null,
  expires_at: 1729646125,
  invoice: 'in_1QCWhOJIILh1w4UF0IuqBHfX',
  invoice_creation: null,
  livemode: false,
  locale: null,
  metadata: {},
  mode: 'subscription',
  payment_intent: null,
  payment_link: null,
  payment_method_collection: 'always',
  payment_method_configuration_details: { id: 'pmc_1MrTV5JIILh1w4UF7JoSIKZo', parent:
 null },
  payment_method_options: { card: { request_three_d_secure: 'automatic' } },
  payment_method_types: [ 'card' ],
  payment_status: 'paid',
  phone_number_collection: { enabled: false },
  recovered_from: null,
  saved_payment_method_options: {
    allow_redisplay_filters: [ 'always' ],
    payment_method_remove: null,
    payment_method_save: null
  },
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  status: 'complete',
  submit_type: null,
  subscription: {
    id: 'sub_1QCWhOJIILh1w4UFrJOiy613',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: false, liability: null },
    billing_cycle_anchor: 1729559750,
    billing_cycle_anchor_config: null,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: { comment: null, feedback: null, reason: null },
    collection_method: 'charge_automatically',
    created: 1729559750,
    currency: 'brl',
    current_period_end: 1732238150,
    current_period_start: 1729559750,
    customer: 'cus_R4g3xMx8XLkEn5',
    days_until_due: null,
    default_payment_method: 'pm_1QCWhNJIILh1w4UFcQu3W3NL',
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    ended_at: null,
    invoice_settings: { account_tax_ids: null, issuer: [Object] },
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1QCWhOJIILh1w4UFrJOiy613'        
    },
    latest_invoice: 'in_1QCWhOJIILh1w4UF0IuqBHfX',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: [Object],
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1QCWHKJIILh1w4UFyIVmg40l',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 4000,
      amount_decimal: '4000',
      billing_scheme: 'per_unit',
      created: 1729558134,
      currency: 'brl',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      meter: null,
      nickname: null,
      product: [Object],
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1729559750,
    status: 'active',
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: { end_behavior: [Object] },
    trial_start: null
  },
  success_url: 'http://localhost:3000/success?session_id={CHECKOUT_SESSION_ID}',     
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: 'hosted',
  url: null
}